### ISSUE TITLE
Translation files

### ISSUE THREAD

**Issue by scandella** [verbb/snipcart-craft-plugin#56]
### What are you trying to do?

Hi,
I want to use this plugin for one feature: the Snipcart's dashboard.
But I can't show it to my client in English.
Could you provide the translation file so I can  create a .fr file?
 
Thanks for your help.
 

### What's your proposed solution?

Providing a translation file.

**Comment by engram-design** [comment]
Added for the next release, see [here](https://github.com/verbb/snipcart/blob/craft-4/src/translations/en/snipcart.php)

**Comment by scandella** [comment]
Nice!
Would it be possible to change the plugin name that appears in the CP panel?
Because "Snipcart" does not mean anything to the client. 

Best.

**Comment by engram-design** [comment]
Sure, added for the next release. To get this early, run `composer require verbb/snipcart:"dev-craft-4 as 2.1.1"`.

**Comment by engram-design** [comment]
Added in [2.1.2](https://github.com/verbb/snipcart/releases/tag/2.1.2)
